server:
  port: 9002
spring:
  application:
    name: admin-server-nacos-security
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      discovery:
        # 不显示admin-server-nacos-security的监控信息
        ignored-services: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848