server:
  port: 9002
spring:
  application:
    name: admin-server-nacos-security
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      discovery:
        # 不显示admin-server-nacos-security的监控信息
        ignored-services: ${spring.application.name}
      notify:
        mail:
          from: xxx@163.com
          to: xxx@gmail.com
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    username: xxx@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: xxxxx
    # 端口号 smtp协议使用25端口  smtps协议使用465端口
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848