server:
  port: 9001
spring:
  application:
    name: admin-client-nacos
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: admin-client.log
