server:
  port: 199
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:99
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: admin-client.log
